# SPDX-FileCopyrightText: 2026 - Canonical Ltd
# SPDX-License-Identifier: Apache-2.0

from pathlib import Path

import pytest

from openstack_hypervisor.ovn_env import OVNEnvError, parse_ovn_env


def _write_ovn_env(path: Path, contents: str) -> Path:
    path.write_text(contents, encoding="utf-8")
    return path


def _assert_invalid(path: Path, *sensitive_values: str) -> None:
    with pytest.raises(OVNEnvError) as exc_info:
        parse_ovn_env(path)

    for value in sensitive_values:
        assert value not in str(exc_info.value)


def test_parse_generated_environment_returns_only_required_connections(tmp_path):
    nb_connection = "ssl:10.0.0.10:6641,ssl:[2001:db8::10]:6641"
    sb_connection = "ssl:10.0.0.10:6642,ssl:[2001:db8::10]:6642"
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        "\n".join(
            [
                "# # Generated by MicroOVN, DO NOT EDIT.",
                "",
                'OVN_INITIAL_NB="10.0.0.10"',
                'OVN_INITIAL_SB="10.0.0.10"',
                f'OVN_NB_CONNECT="{nb_connection}"',
                f"OVN_SB_CONNECT='{sb_connection}'",
                'OVN_LOCAL_IP="10.0.0.20"',
                "",
            ]
        ),
    )

    assert parse_ovn_env(path) == {
        "OVN_NB_CONNECT": nb_connection,
        "OVN_SB_CONNECT": sb_connection,
    }


def test_parse_accepts_microovn_tcp_connections(tmp_path):
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        'OVN_NB_CONNECT="tcp:10.0.0.10:6641"\n' 'OVN_SB_CONNECT="tcp:[2001:db8::10]:6642"\n',
    )

    assert parse_ovn_env(path) == {
        "OVN_NB_CONNECT": "tcp:10.0.0.10:6641",
        "OVN_SB_CONNECT": "tcp:[2001:db8::10]:6642",
    }


@pytest.mark.parametrize("missing_key", ["OVN_NB_CONNECT", "OVN_SB_CONNECT"])
def test_parse_rejects_missing_required_assignment(tmp_path, missing_key):
    values = {
        "OVN_NB_CONNECT": "ssl:10.0.0.10:6641",
        "OVN_SB_CONNECT": "ssl:10.0.0.10:6642",
    }
    del values[missing_key]
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        "".join(f'{key}="{value}"\n' for key, value in values.items()),
    )

    _assert_invalid(path, *values.values())


@pytest.mark.parametrize("duplicate_key", ["OVN_NB_CONNECT", "OVN_SB_CONNECT"])
def test_parse_rejects_duplicate_required_assignment(tmp_path, duplicate_key):
    nb_connection = "ssl:10.0.0.10:6641"
    sb_connection = "ssl:10.0.0.10:6642"
    values = {
        "OVN_NB_CONNECT": nb_connection,
        "OVN_SB_CONNECT": sb_connection,
    }
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        "".join(
            [
                f'{duplicate_key}="{values[duplicate_key]}"\n',
                f'OVN_NB_CONNECT="{nb_connection}"\n',
                f'OVN_SB_CONNECT="{sb_connection}"\n',
            ]
        ),
    )

    _assert_invalid(path, nb_connection, sb_connection)


@pytest.mark.parametrize(
    "malformed_line",
    [
        "OVN_NB_CONNECT=ssl:10.0.0.10:6641",
        'export OVN_NB_CONNECT="ssl:10.0.0.10:6641"',
        'OVN_NB_CONNECT="ssl:10.0.0.10:6641" trailing',
        "not an assignment",
    ],
)
def test_parse_rejects_malformed_assignment_syntax(tmp_path, malformed_line):
    sb_connection = "ssl:10.0.0.10:6642"
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        f'{malformed_line}\nOVN_SB_CONNECT="{sb_connection}"\n',
    )

    _assert_invalid(path, sb_connection)


@pytest.mark.parametrize("empty_value", ['""', "''"])
def test_parse_rejects_empty_required_value(tmp_path, empty_value):
    sb_connection = "ssl:10.0.0.10:6642"
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        f'OVN_NB_CONNECT={empty_value}\nOVN_SB_CONNECT="{sb_connection}"\n',
    )

    _assert_invalid(path, sb_connection)


@pytest.mark.parametrize(
    "unsupported_connection",
    [
        "unix:/run/ovn/ovnnb_db.sock",
        "ssh:10.0.0.10:6641",
        "ssl:ovn-central.internal:6641",
        "ssl:2001:db8::10:6641",
        "ssl:10.0.0.10:0",
        "ssl:10.0.0.10:65536",
        "ssl:10.0.0.10",
        "ssl:10.0.0.10:6641,",
    ],
)
def test_parse_rejects_unsupported_endpoint(tmp_path, unsupported_connection):
    sb_connection = "ssl:10.0.0.10:6642"
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        f'OVN_NB_CONNECT="{unsupported_connection}"\n' f'OVN_SB_CONNECT="{sb_connection}"\n',
    )

    _assert_invalid(path, unsupported_connection, sb_connection)


def test_parse_does_not_execute_assignment_values(tmp_path):
    marker = tmp_path / "executed"
    malicious_value = f"$(touch {marker})"
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        f'OVN_NB_CONNECT="{malicious_value}"\n' 'OVN_SB_CONNECT="ssl:10.0.0.10:6642"\n',
    )

    _assert_invalid(path, malicious_value)
    assert not marker.exists()


def test_parse_rejects_missing_file(tmp_path):
    _assert_invalid(tmp_path / "missing-ovn.env")


def test_parse_rejects_unreadable_file(tmp_path):
    path = _write_ovn_env(
        tmp_path / "ovn.env",
        'OVN_NB_CONNECT="ssl:10.0.0.10:6641"\n' 'OVN_SB_CONNECT="ssl:10.0.0.10:6642"\n',
    )
    path.chmod(0)

    _assert_invalid(path)
